### ISSUE TITLE
failure to run with specific primer set

### ISSUE THREAD

**Issue by MVesuviusC** [MVesuviusC/primerTree#12]
Hey Jim,

I'm trying to run the following primers: algae <- search_primer_pair(name="Algae 23SrDNA","GGACAGAAAGACCCTATGAA","TGAGTGACGGCCTTTCCACT",num_aligns=1000)

When I do I get the following error message:
BLASTing 1 primer combinations
Submitting Primer-BLAST query
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment completed in 117 seconds
Error in (function (pre)  : Parsing failed for 

product length = 375
Forward primer  1      GGACAGAAAGACCCTATGAA  20
Template        19902  ....................  19921

Reverse primer  1      TGAGTGACGGCCTTTCCACT  20
Template        20276  ....C.......C.......  20257
and if I plot the primers I get a tree that looks normal but there are no colored tips. I've tried going through the code but I think the primers are running into a problem when they get to the parse_primer_hits function, but that's getting into html type stuff that's beyond my R-fu. Any idea what might be going on here? It looks like it's getting sequences back since it's putting together a tree, but something in the parsing is mixed up.

Thanks!

**Comment by jimhester** [comment]
1. do a `traceback()` after the error to see exactly where it occurred.
2. I am guessing the parsing failed when it was getting the taxonomy information, look at the taxonomy results manually to figure out why.

**Comment by MVesuviusC** [comment]
Thanks, here is the traceback. The usual taxonomy info in the primerTree object isn't there:
names(algae)
[1] "arguments" "name"      "response" 

traceback()
11: stop("Parsing failed for ", pre_text)
10: (function (pre) 
    {
        pre_text = xmlValue(pre)
        a = getNodeSet(pre, "./preceding-sibling::a[1]")
        if (length(a) <= 0) 
            stop("Parsing failed for ", pre_text)
        ids = parse_a(a[[1]])
        product_length_regex = "product length = (\d+)"
        template_regex = "Template[^\d]+(\d+)[^.ACGT]+([.ACGT]+)[^\d]+(\d+)"
        full_regex = paste("[\S\W]_", product_length_regex, "[\S\W]_?", 
            template_regex, "[\S\W]_", template_regex, "[\S\W]_", 
            sep = "")
        values = str_split(gsub(full_regex, paste("\", 1:8, sep = "", 
            collapse = "|"), pre_text, perl = T), "[|]")[[1]]
        data.frame(ids, product_length = as.numeric(values[1]), mismatch_forward = str_count(values[3], 
            "[ACGT]"), mismatch_reverse = str_count(values[6], "[ACGT]"), 
            forward_start = as.numeric(values[2]), forward_stop = as.numeric(values[4]), 
            reverse_start = as.numeric(values[5]), reverse_stop = as.numeric(values[7]), 
            product_start = min(as.numeric(values[c(2, 4, 5, 7)])), 
            product_stop = max(as.numeric(values[c(2, 4, 5, 7)])))
    })(<pointer: 0x21bdc230>)
9: .Call("RS_XML_xpathEval", doc, .node, as.character(path), namespaces, 
       fun, encoding, addFinalizer, PACKAGE = "XML")
8: xpathApply.XMLInternalDocument(content, "//pre", parse_pre)
7: xpathApply(content, "//pre", parse_pre)
6: rbind.fill(xpathApply(content, "//pre", parse_pre))
5: FUN(X[[1L]], ...)
4: lapply(pieces, .fun, ...)
3: structure(lapply(pieces, .fun, ...), dim = dim(pieces))
2: llply(.data = .data, .fun = .fun, ..., .progress = .progress, 
       .inform = .inform, .parallel = .parallel, .paropts = .paropts)
1: ldply(primer_search$response, primerTree:::parse_primer_hits)

**Comment by jimhester** [comment]
If you run `(parsable_html(algae$response[[1]]))` You will find right above the lines

```
product length = 375
Forward primer 1 GGACAGAAAGACCCTATGAA 20
Template 19902 .................... 19921

Reverse primer 1 TGAGTGACGGCCTTTCCACT 20
Template 20276 ....C.......C....... 20257
```

The HTML contains the following line

```
&gt;<a href="http://www.ncbi.nlm.nih.gov/nucleotide/698348881?from=19902&amp;to=20276&amp;report=gbwithparts" target="new_entrez">KM462873.1</a> Neocystis brevis culture-collection CAUP<czh>:D802 chloroplast, complete genome
```

Critically the `<czh>` in the description is not properly escaped by Primer-BLAST.  This causes the HTML to be malformed and the PrimerTree parsing to fail because it thinks there is a `<czh>` block.

These descriptions were supposed to be stripped out in `parseable_html()`, however in this case there were three different reasons this was not done.

`parseable_html()` has the following definition.

``` r
content = htmlParse(gsub('(viewer.fcgi.*?</a>).*?<pre>\n\n', '\\1\n<pre>', content(response, as='text')))
```

So the regex is looking for a view.fcgi, followed by the end of the link, then the next preformatted block.  It then replaces what is in between the link and the preformatted block (the description) with a newline.

This regex was failing because
1. The description contains a newline, which is not matched by `.` by default.
2. The link for that sequence does not link to the viewer.fcgi, but to `http://www.ncbi.nlm.nih.gov/nucleotide/698348881?from=19902&to=20276&report=gbwithparts`, so the regex was not matching the first part.
3. None of the above would have mattered if the description did not also contain a `<CZH>` which broke the HTML parsing.

So this was basically 3 things all going wrong at once to cause this bug.

The fix is to change the line to

``` r
htmlParse(gsub('("new_entrez".*?</a>).*?<pre>\n\n', '\\1\n<pre>', content(response, as='text')))
```

The best way to diagnose issues like these are to look at the original Primer-Blast results by going to the url in the body (just print the object to get this) then look at the HTML of the page.

You can also view the HTML directly from the object using (in this instance) `httr::content(algae$response[[1]], as='text')`
