### ISSUE TITLE
Error in curl::handle_setform: Insupported value type for form field 'PRIMER_LEFT_INPUT'

### ISSUE THREAD

**Issue by RaSieb** [MVesuviusC/primerTree#28]
```
> devtools::install_github("jimhester/primerTree")
Downloading GitHub repo jimhester/primerTree@master
from URL https://api.github.com/repos/jimhester/primerTree/zipball/master
Installing primerTree
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/wh/ngnn010j5k3d6b590f225flw0000gn/T/RtmpXMoesV/devtools7a501a74e7dc/jimhester-primerTree-018e066'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘primerTree’ ...
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c read_dna.c -o read_dna.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o primerTree.so read_dna.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/primerTree/libs
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (primerTree)
> library(primerTree)
Loading required package: directlabels
Loading required package: gridExtra
> mammals_16S = search_primer_pair(name='Mammals 16S', 'CGGTTGGGGTGACCTCGGA', 'GCTGTTATCCCTAGGGTAACT')
BLASTing 1 primer combinations
No encoding supplied: defaulting to UTF-8.
Submitting Primer-BLAST query
Error in curl::handle_setform(handle, .list = req$fields) : 
  Insupported value type for form field 'PRIMER_LEFT_INPUT'.

> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] primerTree_1.0.3        gridExtra_2.3           directlabels_2017.03.31

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     magrittr_1.5     devtools_1.13.3  munsell_0.4.3    colorspace_1.3-2 ape_4.1          lattice_0.20-35  R6_2.2.2        
 [9] rlang_0.1.2      quadprog_1.5-5   foreach_1.4.3    stringr_1.2.0    plyr_1.8.4       httr_1.3.1       tools_3.4.1      parallel_3.4.1  
[17] grid_3.4.1       gtable_0.2.0     nlme_3.1-131     git2r_0.19.0     withr_2.0.0      iterators_1.0.8  lazyeval_0.2.0   digest_0.6.12   
[25] tibble_1.3.4     reshape2_1.4.2   ggplot2_2.2.1    codetools_0.2-15 curl_2.8.1       memoise_1.1.0    stringi_1.1.5    compiler_3.4.1  
[33] scales_0.5.0     XML_3.98-1.9     lubridate_1.6.0 

```

**Comment by MVesuviusC** [comment]
I've run into the same issue when trying to re-install primerTree. Digging into the code, it looks like the "enumerate_primers" function creates a dataframe of the primer combinations, but they are stored as factors and not as characters. I'm guessing that an update to curl changed behavior at some point and it is throwing the error message since it doesn't like the primer being a factor... I wrote a fix in a fork and will push it back. Here is some info documenting the behavior:

# old code:
>primers = primerTree:::enumerate_primers('CGGTTGGGGTGACCTCGGN', 'GCTGTTATCCCTAGGGTAACN')
>typeof(primers$forward)
"integer"
> is.factor(primers$forward)
[1] TRUE
> summary(primers)
                forward                   reverse
 CGGTTGGGGTGACCTCGGA:4   GCTGTTATCCCTAGGGTAACA:4
 CGGTTGGGGTGACCTCGGC:4   GCTGTTATCCCTAGGGTAACC:4
 CGGTTGGGGTGACCTCGGG:4   GCTGTTATCCCTAGGGTAACG:4
 CGGTTGGGGTGACCTCGGT:4   GCTGTTATCCCTAGGGTAACT:4
> primers
               forward               reverse
1  CGGTTGGGGTGACCTCGGA GCTGTTATCCCTAGGGTAACA
2  CGGTTGGGGTGACCTCGGC GCTGTTATCCCTAGGGTAACA
3  CGGTTGGGGTGACCTCGGG GCTGTTATCCCTAGGGTAACA
4  CGGTTGGGGTGACCTCGGT GCTGTTATCCCTAGGGTAACA
5  CGGTTGGGGTGACCTCGGA GCTGTTATCCCTAGGGTAACC
6  CGGTTGGGGTGACCTCGGC GCTGTTATCCCTAGGGTAACC
7  CGGTTGGGGTGACCTCGGG GCTGTTATCCCTAGGGTAACC
8  CGGTTGGGGTGACCTCGGT GCTGTTATCCCTAGGGTAACC
9  CGGTTGGGGTGACCTCGGA GCTGTTATCCCTAGGGTAACG
10 CGGTTGGGGTGACCTCGGC GCTGTTATCCCTAGGGTAACG
11 CGGTTGGGGTGACCTCGGG GCTGTTATCCCTAGGGTAACG
12 CGGTTGGGGTGACCTCGGT GCTGTTATCCCTAGGGTAACG
13 CGGTTGGGGTGACCTCGGA GCTGTTATCCCTAGGGTAACT
14 CGGTTGGGGTGACCTCGGC GCTGTTATCCCTAGGGTAACT
15 CGGTTGGGGTGACCTCGGG GCTGTTATCCCTAGGGTAACT
16 CGGTTGGGGTGACCTCGGT GCTGTTATCCCTAGGGTAACT


# new code:
> primers = primerTree:::enumerate_primers('CGGTTGGGGTGACCTCGGN', 'GCTGTTATCCCTAGGGTAACN')
> typeof(primers$forward)
[1] "character"
> is.factor(primers$forward)
[1] FALSE
> summary(primers)
   forward            reverse
 Length:16          Length:16
 Class :character   Class :character
 Mode  :character   Mode  :character
> primers
               forward               reverse
1  CGGTTGGGGTGACCTCGGA GCTGTTATCCCTAGGGTAACA
2  CGGTTGGGGTGACCTCGGC GCTGTTATCCCTAGGGTAACA
3  CGGTTGGGGTGACCTCGGG GCTGTTATCCCTAGGGTAACA
4  CGGTTGGGGTGACCTCGGT GCTGTTATCCCTAGGGTAACA
5  CGGTTGGGGTGACCTCGGA GCTGTTATCCCTAGGGTAACC
6  CGGTTGGGGTGACCTCGGC GCTGTTATCCCTAGGGTAACC
7  CGGTTGGGGTGACCTCGGG GCTGTTATCCCTAGGGTAACC
8  CGGTTGGGGTGACCTCGGT GCTGTTATCCCTAGGGTAACC
9  CGGTTGGGGTGACCTCGGA GCTGTTATCCCTAGGGTAACG
10 CGGTTGGGGTGACCTCGGC GCTGTTATCCCTAGGGTAACG
11 CGGTTGGGGTGACCTCGGG GCTGTTATCCCTAGGGTAACG
12 CGGTTGGGGTGACCTCGGT GCTGTTATCCCTAGGGTAACG
13 CGGTTGGGGTGACCTCGGA GCTGTTATCCCTAGGGTAACT
14 CGGTTGGGGTGACCTCGGC GCTGTTATCCCTAGGGTAACT
15 CGGTTGGGGTGACCTCGGG GCTGTTATCCCTAGGGTAACT
16 CGGTTGGGGTGACCTCGGT GCTGTTATCCCTAGGGTAACT

**Comment by haoeric** [comment]
the problem is still there

**Comment by StephanieHowes** [comment]
Hello, I am very excited to try PrimerTree but I have been experiencing the same problem.  Is there any word on an update to the program?

**Comment by MVesuviusC** [comment]
I'm working on a fix, but the underlying issue is a bit deeper than I expected, so it's taking a bit of time. I hope to get this taken care of soon though!

**Comment by rrcutler** [comment]
Hello, I too am experiencing the same problem. Has this been fixed yet?

**Comment by jimhester** [comment]
Should now be fixed.

**Comment by rrcutler** [comment]
I think I am using the latest version, 1.0.3.

Could I be doing something else wrong?
`> ttyh1.L_1 <- search_primer_pair(name = "ttyh1.L_1", forward = 'ATTCTCCCTTTGTTTACTGCT', reverse = 'CTCTATTTCTCCATTCAGCCA', num_aligns = 100)
BLASTing 1 primer combinations
request failed, retry attempt 1request failed, retry attempt 2request failed, retry attempt 3request failed, retry attempt 4request failed, retry attempt 5No encoding supplied: defaulting to UTF-8.
Submitting Primer-BLAST query
Error in curl::handle_setform(handle, .list = req$fields) : 
  Unsupported value type for form field 'PRIMER_LEFT_INPUT'.`

**Comment by MVesuviusC** [comment]
It worked on my end, try reinstalling it directly from github:
library(devtools)
devtools::install_github("jimhester/primerTree")
library(primerTree)
